/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js. It is included here because
// the repository snapshot we received was incomplete and did not contain it.
